# AUTOTASK CONFIG =================================================================
# Auto task parameters

TaskRequester:
  machines:
    # Examples:
    # machine_name:
    #     mode_operation: "combine"  # (station, combine)
    #     sku: "RF370CB"
    #     dispenser: "wp1--mpickup"
    #     ingestor: "wp1--dropoff"
    #     pickup_stations: ["pk1","pk2","pk3"]
    #     dropoff_stations: ["do1","do2","do3"]
    #     station_names: ["clr001--dropoff", "clr002--dropoff",
    #                     "clr003--dropoff", "clr004--dropoff",
    #                     "clr005--dropoff"]
    
    # nqvl_m104:
    #     mode_operation: "combine"  # (station, combine)
    #     sku: "E29"
    #     dispenser: "m104--mpickup"
    #     ingestor: "m104--dropoff"
    #     pickup_stations: ["station001--pickup", "station002--pickup",
    #                       "station003--pickup", "station004--pickup"]
    #     dropoff_stations: ["station001--dropoff", "station002--dropoff"]
    #     station_names: ["station001--pickup", "station002--pickup",
    #                     "station003--pickup", "station004--pickup",
    #                     "station001--dropoff", "station002--dropoff"]

  stations:
    # Examples:
    # line82--pickup:
    #   step1:
    #     sku: "RF370CB_TTR"
    #     pickup_station: clr82--pickup
    #     dropoff_stations: ["line82--dropoff"]
    #   step2:
    #     sku: "RF370CB_TTR"
    #     pickup_station: line82--pickup
    #     dropoff_stations: ["clr001--dropoff", "clr002--dropoff"]