# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_vdm"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.7, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.2 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 80.0 # Ahr
    charging_current: 17.0 # A
  mechanical_system:
    mass: 6.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 5.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing" # [park, charge, nothing]
    # action_categories: ["custom_mission_1"]

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for robot1
  amr_001:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5.0
      start:
        map_name: "L1"
        waypoint: "amr001_start"
        orientation: 0.0 # radians
      charger:
        waypoint: "amr001--charger"
  
  # Configuration for robot2
  amr_002:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5.0
      start:
        map_name: "L1"
        waypoint: "amr002_start"
        orientation: 0.0 # radians
      charger:
        waypoint: "amr002--charger"

# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # Configuration for clr55--dropoff:
  clr55--dropoff:
    front_dock: "clr55DOFD"
    orientation: -1.57199
    rotate_to_dock: 180
    custom_dock: 
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for clr56--dropoff:
  clr56--dropoff:
    front_dock: "clr56DOFD"
    orientation: -1.57199
    rotate_to_dock: 180
    # custom_dock: 
    #   rotate_angle: 45
    #   rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for clr55--pickup:
  clr55--pickup:
    front_dock: "clr55PKFD"
    orientation: 1.571
    rotate_to_dock: -90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise
  
  # Configuration for clr56--pickup:
  clr56--pickup:
    front_dock: "clr56PKFD"
    orientation: 1.571
    rotate_to_dock: -90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for line55--dropoff:
  line55--dropoff:
    front_dock: "line55DOFD"
    orientation: -1.57199
    rotate_to_dock: 90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for line55--pickup:
  line55--pickup:
    front_dock: "line55PKFD"
    orientation: 1.57199
    rotate_to_dock: -90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for line56--dropoff:
  line56--dropoff:
    front_dock: "line56DOFD"
    orientation: -1.57199
    rotate_to_dock: -90
    custom_dock: 
      rotate_angle: 45
      rotate_orientation: 0 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for line56--pickup:
  line56--pickup:
    front_dock: "line56PKFD"
    orientation: -1.57199
    rotate_to_dock: -90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 0 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for amr_001--charger:
  amr001--charger:
    front_dock: "amr001_start"
    orientation: 0.00
    rotate_to_dock: 90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for amr_002--charger:
  amr002--charger:
    front_dock: "amr002_start"
    orientation: 0.00
    rotate_to_dock: 90
    # custom_dock: 
    #   rotate_angle: 30
    #   rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise


