# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_tayrua"
  limits:
    linear: [0.7, 1.5] # velocity, acceleration
    angular: [0.7, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.4 # radius in m
    vicinity: 0.5 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 60.0 # Ahr
    charging_current: 12.0 # A
  mechanical_system:
    mass: 100.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.8 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 5.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  charger_server_running: True  # Server charge is running or not
  robots:
    # Here the user is expected to append the configuration for each robot in the fleet.
    amr001:
      charger: "charger001--charge"
    amr002:
      charger: "charger002--charge"
  
fleet_manager:
  ip: "127.0.0.1"
  port: 7001
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0


# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # /******************** TP2 *********************/
  clr55--pickup:
    distance_go_out: 0.90

  clr55--dropoff:
    distance_go_out: 2.5
    rotate_to_dock: 0
    custom_dock:
      rotate_angle: 30
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  line55--pickup:
    distance_go_out: 0.85

  line55--dropoff:
    distance_go_out: 0.65

  # /******************** TP3 *********************/
  clr90--pickup:
    distance_go_out: 0.90

  clr90--dropoff:
    distance_go_out: 0.70
    rotate_to_dock: 90

  line90--pickup:
    distance_go_out: 0.85

  line90--dropoff:
    distance_go_out: 0.65

  charger001--charge:
    distance_go_out: -0.65

  charger002--charge:
    distance_go_out: -0.65

# up: 1.57199, down: -1.57199, right: 0.0, left: 3.14  
vertexs:
  # ------TP2------:
  # Line55:
  clr55_PKFD: 0.0
  clr55_DOFD: 1.57199
  line55_PKFD: 0.0
  line55_DOFD: 0.0
  park_tp2_001: 3.14
  waiting_for_lift_tp2: 1.57199
  lift001-L1: [1.57199, True]
  # ------TP3------:
  # Line90:
  clr90_PKFD: 0.0
  clr90_DOFD: 0.0
  line90_PKFD: -1.57199
  line90_DOFD: -1.57199
  waiting_for_lift_tp3: 1.57199
  tp3_forward_1: 0.0
  lift001-L2: [1.57199, True]

machines: []
stations: []