# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_tayrua"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22011
    user: "some_user"
    password: "some_password"
  limits:
    # linear: [0.7, 1.5] # velocity, acceleration
    # angular: [0.7, 2.0] # velocity, acceleration
    linear: [1.2, 2.5] # velocity, acceleration
    angular: [1.2, 3.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 1.0 # radius in m
    vicinity: 1.2 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 80.0 # Ahr
    charging_current: 17.0 # A
  mechanical_system:
    mass: 6.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.80 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 5.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing" # [park, charge, nothing]
    # action_categories: ["custom_mission_1"]
  
  server_charger_running: True  # Server charge is running or not

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for robot1
  amr_001:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5.0
      start:
        map_name: "L2"
        waypoint: "amr-start"
        orientation: 0.0 # radians
      charger:
        waypoint: "charger001--charge"
  
  # Configuration for robot2
  amr_002:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 5.0
      start:
        map_name: "L2"
        # waypoint: "amr-start"
        orientation: 0.0 # radians
      charger:
        # waypoint: "charger001--charge"
        waypoint: "amr-start"

# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # /******************** TP3 *********************/
  # Configuration for line90--pickup:
  line90--pickup:
    machine: False  # Vị trí docking này là máy hay trạm thô
    distance_go_out: 0.9
    rotate_to_dock: 90
    custom_dock: 
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for line90--dropoff:
  line90--dropoff:
    machine: False # Vị trí docking này là máy hay trạm thô
    distance_go_out: 0.9
    rotate_to_dock: -90
    custom_dock: 
      rotate_angle: 90
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for tramlay1--pickup:
  tramlay1--pickup:
    machine: False  # Vị trí docking này là máy hay trạm thô
    distance_go_out: 0.90
    rotate_to_dock: 90

  # Configuration for tramtha1--dropoff:
  tramtha1--dropoff:
    machine: False  # Vị trí docking này là máy hay trạm thô
    distance_go_out: 0.62
    rotate_to_dock: -180
    custom_dock:
      rotate_angle: 0
      rotate_orientation: 0 # 0: both, # 1: counter clockwise, 2: clockwise

  # Configuration for charger001--charge:
  charger001--charge:
    machine: False
    rotate_to_dock: -90
    distance_go_out: -0.62

vertexs:
  tramlay1PKFD: [1.57199, False]
  tramtha1DOFD: [1.57199, False]
  line90PKFD: 0.0
  line90DOFD: -1.59
  chargerFD001: 1.57199
  # lift-001: [1.57199, True]

machines: ["nqvlm104"]
stations: ["tramlay1", "tramlay2", "tramlay3", "tramlay4", "tramtha1", "tramtha2"]