# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_lk1"
  limits:
    linear: [0.6, 1.6] # velocity, acceleration
    angular: [0.6, 1.6] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 1.0 # radius in m
    vicinity: 1.2 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 80.0 # Ahr
    charging_current: 12.0 # A
  mechanical_system:
    mass: 100.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.15 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.8 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 5.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
  finishing_request: "nothing" # [park, charge, nothing]
  responsive_wait: False # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  charger_server_running: False  # Server charge is running or not
  distance_tolerance: 0.3 # Distance_tolerance to the next destination if destination is not last
  robots:
    # Here the user is expected to append the configuration for each robot in the fleet.
    amr001:
      charger: "charger001--charge"
      finishing_request: 
        type: "park" # [park, charge, nothing]
        waypoint_name: "park001"
fleet_manager:
  ip: "127.0.0.1"
  port: 7001
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0


# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # rotate_to_dock: Use (-) or (+) to define value
  # rotate_orientation: Use clockwise or counter clockwise
  #                          --------------
  #                          |            |
  #                          |            |
  #                          |   ROBOT    |
  #                          |            |
  #                          |            |
  #                          --------------
  #                              |    |
  #                              |    |
  #                              |    |
  #                              |    |
  #    Clockwise (-)(LEFT) <---- `````` ----> Counter clockwise (+)(RIGHT)

  # full dock config:
  # dock_name:
  #   machine_name: nqvlm104
  #   response_state: line90_ins--pickup
  #   go_in_dock: [rot:0]
  #   go_out_dock: [mov:10, rot:30]
  #   tag_names: []
  #   limits:
  #     rotate_angle: 30
  #     rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise   
  # /******************** LK1 *********************/
  # Dropoffs:
  station24101--dropoff:
    go_out_dock: [mov:0.65]

  station24102--dropoff:
    go_out_dock: [mov:0.65]

  station24201--dropoff:
    go_out_dock: [mov:0.65]

  station24202--dropoff:
    # go_in_dock: [rot:90]
    go_out_dock: [mov:0.65]

  D241--dropoff:
    # machine_name: D241
    go_in_dock: [rot:-180, mov:-0.1]
    go_out_dock: [mov:1.50]
    limits:
      rotate_angle: 30
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  D242--mdropoff:
    machine_name: D242
    go_in_dock: [rot:-90, mov:-0.1]
    go_out_dock: [mov:1.50]
    limits:
      rotate_angle: 30
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # Pickups:
  station001--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.85]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]

  station002--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.85]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]

  station003--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.85]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]

  station004--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.85]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]

  D241--pickup:
    # machine_name: D241
    go_in_dock: [rot:90, mov:-0.27]
    go_out_dock: [mov:1.8]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]
    limits:
      rotate_angle: 30
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  D242--mpickup:
    machine_name: D242
    go_in_dock: [rot:90, mov:-0.27]
    go_out_dock: [mov:1.8]
    tag_names: [tag_frame_0, tag_frame_1, tag_frame_2, tag_frame_3, tag_frame_4,
                tag_frame_5, tag_frame_6, tag_frame_7, tag_frame_8, tag_frame_9]
    limits:
      rotate_angle: 30
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### CHARGERS
  charger001--charge:
    go_out_dock: [mov:-0.7]


# up: 1.57199 (y), down: -1.57199 (-y), right: 0.0 (x), left: 3.14 (-x) (See map frame below)
#             ^ y
#             |
#             |
#             |
#             |
#            -|----------> x
# Orientation of vertexs defined through map frame coordinate above
# Note: 0 = 0.0, 30 = 0.5236, 45 = 0.7854, 60 = 1.0472, 90 = 1.5708
#       120 = 2.0944, 135 = 2.3562, 150 = 2.618, 180 = 3.1416
vertexs:
  park001: 1.57199
  station24101_DOFD: 0.0
  station24102_DOFD: 0.0  
  station24201_DOFD: 0.0
  station24202_DOFD: 0.0
  D241_DOFD: 1.57199
  D242_DOFD: 0.0
  station001_PKFD: -1.57199
  station002_PKFD: -1.57199
  station003_PKFD: -1.57199
  station004_PKFD: -1.57199
  D241_PKFD: 3.14
  D242_PKFD: 3.14

