# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_tp2"
  limits:
    linear: [0.5, 0.9] # velocity, acceleration
    angular: [0.5, 1.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.5 # radius in m
    vicinity: 0.6 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 60.0 # Ahr
    charging_current: 12.0 # A
  mechanical_system:
    mass: 100.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.8 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 5.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  charger_server_running: False  # Server charge is running or not
  distance_tolerance: 0.2 # Distance_tolerance to the next destination if destination is not last
  robots:
    # Here the user is expected to append the configuration for each robot in the fleet.
    amr004:
      charger: "charger001--charge"
    amr005:
      charger: "charger001--charge"

fleet_manager:
  ip: "127.0.0.1"
  port: 7001
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0


# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # rotate_to_dock: Use (-) or (+) to define value
  # rotate_orientation: Use clockwise or counter clockwise
  #                          --------------
  #                          |            |
  #                          |            |
  #                          |   ROBOT    |
  #                          |            |
  #                          |            |
  #                          --------------
  #                              |    |
  #                              |    |
  #                              |    |
  #                              |    |
  #    Clockwise (-)(LEFT) <---- `````` ----> Counter clockwise (+)(RIGHT)

  # /******************** TP2 *********************/
  # LINE 55
  clr55--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_0, tag_frame_2, tag_frame_3]

  clr55--dropoff:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  line55--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.85]
    tag_names: [tag_frame_0, tag_frame_2, tag_frame_3]

  line55--dropoff:
    go_in_dock: [rot:90]
    go_out_dock: [mov:0.65]

  # LINE 56
  clr56--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_4]

  clr56--dropoff:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  line56--pickup:
    go_out_dock: [mov:1.3, rot:-90]
    tag_names: [tag_frame_4]
    limits:
      rotate_angle: 30
      rotate_orientation: 0 # 0: both, # 1: counter clockwise, 2: clockwise

  line56--dropoff:
    go_out_dock: [mov:0.4, rot:-90]  
    limits:
      rotate_angle: 45
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  # LINE 82
  clr82--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 83
  clr83--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 84
  clr84--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 85
  clr85--pickup:
    go_in_dock: [rot:-180]
    go_out_dock: [mov:0.77, rot:-45, mov:0.3, rot:45]
    tag_names: [tag_frame_1]

  # LINE 86
  clr86--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 87
  clr87--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 88
  clr88--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 89
  clr89--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # LINE 90
  clr90--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_1]

  # TTR dropoff tp3:
  clr001--dropoff:
    go_out_dock: [mov:0.65, rot:90, mov:-0.4, rot:-180]
    limits:
      rotate_angle: 45
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  clr002--dropoff:
    go_out_dock: [mov:0.65]

  clr003--dropoff:
    go_out_dock: [mov:0.65]

  clr004--dropoff:
    go_out_dock: [mov:0.65]

  clr005--dropoff:
    go_out_dock: [mov:0.65]

  # /******************** TP3 *********************/
  # LINE82:
  transit82_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit82_str--dropoff:
    response_state: transit82_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE83:
  transit83_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit83_str--dropoff:
    response_state: transit83_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE84:
  transit84_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit84_str--dropoff:
    response_state: transit84_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE85:
  transit85_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit85_str--dropoff:
    response_state: transit85_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE86:
  transit86_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit86_str--dropoff:
    response_state: transit86_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE87:
  transit87_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit87_str--dropoff:
    response_state: transit87_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE88:
  transit88_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit88_str--dropoff:
    response_state: transit88_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE89:
  transit89_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit89_str--dropoff:
    response_state: transit89_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # LINE90:
  transit90_ttr--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:1.0]
    tag_names: [tag_frame_1]

  transit90_str--dropoff:
    response_state: transit90_str--pickup
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.65]

  # Chargers
  charger001--charge:
    go_out_dock: [mov:-0.7]

  # full dock config:
  # dock_name:
  #   machine_name: nqvlm104
  #   response_state: line90_ins--pickup
  #   go_in_dock: [rot:0]
  #   go_out_dock: [mov:10, rot:30]
  #   tag_names: []
  #   limits:
  #     rotate_angle: 30
  #     rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise    


# up: 1.57199 (y), down: -1.57199 (-y), right: 0.0 (x), left: 3.14 (-x) (See map frame below)
#             ^ y
#             |
#             |
#             |
#             |
#            -|----------> x
# Orientation of vertexs defined through map frame coordinate above
# Note: 0 = 0.0, 30 = 0.5236, 45 = 0.7854, 60 = 1.0472, 90 = 1.5708
#       120 = 2.0944, 135 = 2.3562, 150 = 2.618, 180 = 3.1416
vertexs:
  # ------TP2------:
  park_tp2_001: 3.14
  waiting_for_lift_tp2: 1.57199
  lift001-L1: [1.57199, True]
  # LINE 55:
  # clr55_PKFD: 3.14
  # clr55_DOFD: 3.14
  line55_PKFD: 1.57199
  line55_DOFD: -1.5708
  # LINE 56:
  # clr56_PKFD: 3.14
  # clr56_DOFD: 3.14
  line56_PKFD: 0.0
  line56_DOFD: 1.57199
  line56_lane_custom2: -1.57199
  line56_lane_custom3: 3.14
  # STR:
  # clr82_PKFD:  1.57199
  # clr83_PKFD:  1.57199
  # clr84_PKFD:  1.57199
  # clr85_PKFD:  1.57199
  # clr86_PKFD:  3.14
  # clr87_PKFD:  3.14
  # clr88_PKFD:  3.14
  # clr89_PKFD:  3.14
  # clr90_PKFD:  3.14
  # TTR:
  clr001_DOFD: 3.14
  clr002_DOFD: 3.14
  clr003_DOFD: 3.14
  clr004_DOFD: 3.14
  clr005_DOFD: 3.14

  # ------TP3------:
  # TTR:
  # transit82_ttr_PKFD: -1.57199
  # transit83_ttr_PKFD: -1.57199
  # transit84_ttr_PKFD: -1.57199
  # transit85_ttr_PKFD: -1.57199
  # transit86_ttr_PKFD: -1.57199
  # transit87_ttr_PKFD: -1.57199
  # transit88_ttr_PKFD: -1.57199
  # transit89_ttr_PKFD: -1.57199
  # transit90_ttr_PKFD: -1.57199
  # STR:
  # transit82_str_DOFD: 1.57199
  # transit83_str_DOFD: 1.57199
  # transit84_str_DOFD: 1.57199
  # transit85_str_DOFD: 1.57199
  # transit86_str_DOFD: 1.57199
  # transit87_str_DOFD: 1.57199
  # transit88_str_DOFD: 1.57199
  # transit89_str_DOFD: 1.57199
  # transit90_str_DOFD: 1.57199
