# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "amr_tp3"
  limits:
    linear: [0.8, 0.9] # velocity, acceleration
    angular: [0.7, 1.2] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.45 # radius in m
    vicinity: 0.5 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 60.0 # Ahr
    charging_current: 12.0 # A
  mechanical_system:
    mass: 100.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.8 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
  finishing_request: "charge" # [park, charge, nothing]
  responsive_wait: False # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  use_parking_reservations: True
  reassign_task_interval: 60 # seconds, specify how often a task reassignment should be triggered in the fleet
  # max_merge_waypoint_distance: 0.3
  charger_server_running: False  # Server charge is running or not
  distance_tolerance: 0.3 # Distance_tolerance to the next destination if destination is not last
  robots:
    # Here the user is expected to append the configuration for each robot in the fleet.
    amr001:
    amr002:
    amr003:
    amr005:

fleet_manager:
  ip: "127.0.0.1"
  port: 7001
  user: "some_user"
  password: "some_password"
  robot_state_update_frequency: 10.0


# Docks config:
docks:
  # Here the user is expected to append the configuration for each dock in the fleet
  # rotate_to_dock: Use (-) or (+) to define value
  # rotate_orientation: Use clockwise or counter clockwise
  #                          --------------
  #                          |            |
  #                          |            |
  #                          |   ROBOT    |
  #                          |            |
  #                          |            |
  #                          --------------
  #                              |    |
  #                              |    |
  #                              |    |
  #                              |    |
  #    Clockwise (-)(LEFT) <---- `````` ----> Counter clockwise (+)(RIGHT)

  ###### TP3 ######

  ### LINE 82
  clr82--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_4]
  
  line82--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-90]
    tag_names: [tag_frame_4]

  line82--dropoff:
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### LINE 83
  clr83--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_5]
  
  line83--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.65, rot:-30, mov:0.56]
    tag_names: [tag_frame_5]

  line83--dropoff:
    go_in_dock: [mov:-0.5]
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### LINE 84
  clr84--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_6]
  
  line84--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.4, rot:-30, mov:0.5]
    tag_names: [tag_frame_6]

  line84--dropoff:
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### LINE 85
  clr85--pickup:
    go_in_dock: [rot:-180]
    go_out_dock: [mov:0.77]
    tag_names: [tag_frame_7]
  
  line85--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.65, rot:-30, mov:0.56]
    tag_names: [tag_frame_7]

  line85--dropoff:
    go_in_dock: [mov:-0.5]
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### LINE 86
  clr86--pickup:
    go_in_dock: [rot:90]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_8]
  
  line86--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.35, rot:-30, mov:0.4]
    tag_names: [tag_frame_8]

  line86--dropoff:
    go_out_dock: [mov:0.7]

  ### LINE 87
  clr87--pickup:
    go_in_dock: [rot:90]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_9]
  
  line87--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.35, rot:-30, mov:0.4]
    tag_names: [tag_frame_9]

  line87--dropoff:
    go_out_dock: [mov:0.7]

  ### LINE 88
  clr88--pickup:
    go_in_dock: [rot:90]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_10]

  ### LINE 89
  clr89--pickup:
    go_in_dock: [rot:75]
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_11]
  
  line89--pickup:
    go_in_dock: [rot:-90]
    go_out_dock: [mov:0.75, rot:-60, mov:-0.55, rot:-30, mov:0.52]
    tag_names: [tag_frame_11]

  line89--dropoff:
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### LINE 90
  clr90--pickup:
    go_out_dock: [mov:0.90]
    tag_names: [tag_frame_12]
  
  line90--pickup:
    go_in_dock: [rot:180]
    go_out_dock: [mov:0.80]
    tag_names: [tag_frame_12]

  line90--dropoff:
    go_in_dock: [mov:-0.5]
    go_out_dock: [mov:0.7]
    limits:
      rotate_angle: 45
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  ### DOI MA HANG
  doimahang01--dropoff:
    go_in_dock: [rot:-90, mov:-0.40]
    go_out_dock: [mov:0.9, rot:-90]
    limits:
      rotate_angle: 30
      rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise

  doimahang02--dropoff:
    go_in_dock: [rot:-90, mov:-0.43]
    go_out_dock: [mov:0.9, rot:-90]
    limits:
      rotate_angle: 30
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  ### CLEANINGROOM TTR COMMON DROPOFF:
  clr001--dropoff:
    go_out_dock: [mov:0.65]

  clr002--dropoff:
    go_out_dock: [mov:0.65]

  clr003--dropoff:
    go_out_dock: [mov:0.65]

  clr004--dropoff:
    go_out_dock: [mov:0.65]

  clr005--dropoff:
    go_out_dock: [mov:0.65, rot:90, mov:-0.4, rot:-180]
    limits:
      rotate_angle: 45
      rotate_orientation: 1 # 0: both, # 1: counter clockwise, 2: clockwise

  ### CHARGERS
  charger001--charge:
    go_out_dock: [mov:-0.9]
    
  charger003--charge:
    go_out_dock: [mov:-1.1]

  charger004--charge:
    go_out_dock: [mov:-1.1]

  # full dock config:
  # dock_name:
  #   machine_name: nqvlm104
  #   response_state: line90_ins--pickup
  #   go_in_dock: [rot:0]
  #   go_out_dock: [mov:10, rot:30]
  #   tag_names: []
  #   limits:
  #     rotate_angle: 30
  #     rotate_orientation: 2 # 0: both, # 1: counter clockwise, 2: clockwise    


# up: 1.57199 (y), down: -1.57199 (-y), right: 0.0 (x), left: 3.14 (-x) (See map frame below)
#             ^ y
#             |
#             |
#             |
#             |
#            -|----------> x
# Orientation of vertexs defined through map frame coordinate above
# Note: 0 = 0.0, 30 = 0.5236, 45 = 0.7854, 60 = 1.0472, 90 = 1.5708
#       120 = 2.0944, 135 = 2.3562, 150 = 2.618, 180 = 3.1416
vertexs:
  ### TP2
  lift001-L1: [1.57199, True]
  waiting_for_lift_201: 1.57199
  lift_parking_201: 3.14
  lift_parking_202: 3.14

  ### TP3
  lift_parking_301: 1.5708
  parking_301: 1.5708
  parking_302: 3.14

  ### CLEANINGROOM TTR COMMON DROPOFF:
  clr001_DOFD: 3.14
  clr002_DOFD: 3.14
  clr003_DOFD: 3.14
  clr004_DOFD: 3.14
  clr005_DOFD: 3.14

  ### LINE 82
  line82_PKFD: -1.57199
  line82_DOFD: 1.57199

  ### LINE 83
  line83_PKFD: 1.57199
  line83_DOFD: -1.57199

  ### LINE 84
  line84_PKFD: -1.57199
  line84_DOFD: 1.57199

  ### LINE 85
  line85_PKFD: 1.57199
  line85_DOFD: -1.57199

  ### LINE 86
  line86_PKFD: 1.5184
  line86_DOFD: -1.57199
  clr86_PKFD: 1.57199

  ### LINE 87
  line87_PKFD: 1.57199
  line87_DOFD: -1.57199
  clr87_PKFD: 1.57199

  ### LINE 88
  clr88_PKFD: 1.57199

  ### LINE 89
  line89_PKFD: -1.57199
  line89_DOFD:  1.57199
  clr89_PKFD: 1.8326

  ### LINE 90
  # line90_PKFD: 3.14
  line90_DOFD: -1.57199
  clr90_PKFD: 3.14

  ### DOI MA HANG
  doimahang01_DOFD: -1.57199
  doimahang02_DOFD: -1.57199